### ISSUE TITLE
[BUG] Types are incorrect for optional types

### ISSUE THREAD

**Issue by nh13** [vemel/mypy_boto3_builder#30]
Types are incorrect for optional types.  This causes confusion and typing errors.

For example, in `mypy_boto3_batch.client`:

```
    def submit_job(
        self,
        jobName: str,
        jobQueue: str,
        jobDefinition: str,
        arrayProperties: ArrayPropertiesTypeDef = None,
        dependsOn: List["JobDependencyTypeDef"] = None,
        parameters: Dict[str, str] = None,
        containerOverrides: "ContainerOverridesTypeDef" = None,
        nodeOverrides: NodeOverridesTypeDef = None,
        retryStrategy: "RetryStrategyTypeDef" = None,
        timeout: "JobTimeoutTypeDef" = None,
    ) -> SubmitJobResponseTypeDef:
```

The `nodeOverrides` should have type `Optional[NodeOverridesTypeDef]`.

This matters, because passing an empty dictionary (`{}`) is different than passing in `None`.  The former causes an error if we specify container overrides (non-empty dict) and an empty dict for node overrides, versus no error if the latter is `None`.

I'd be happy to submit a PR to this repo, or it may be the case `boto3` needs to be updated, but a simple search couldn't find `submit_job` in this repo or that one.  For now I can ask the typer to ignore, but that defeats type annotations.

**Comment by nh13** [comment]
Related to: https://github.com/boto/botocore/issues/2075

**Comment by vemel** [comment]
I agree, but https://github.com/boto/botocore/issues/2075 is the main reason why i did not wrap everything in `Optional[...]`. I encountered this behavior with `dynamodb` where not passing argument and passing `None` is different. 

For now I think the best solution is to wait until this is resolved in `botocore`.

And I cannot replace `None` with ellipsis, because original functions do not have these arguemnts, they have `*args, **kwargs`, so annotation will become invalid.

**Comment by vemel** [comment]
Hello @nh13 !

I started a new ambitious project `boto3-next`. The goal to make an easy-to-use `boto3` for py36+

Marked things are done:

- [x] Fully type annotated
- [x] Backwards compatible to be a drop-in replacement
- [x] Py39 support
- [x] Fixes for bugs discovered by typing
- [x] Code style
- [ ] Type annotations for services (I want to adapt `mypy_boto3_builder` a bit)

For now I have heavily rewritten https://github.com/vemel/boto3, but it will not be merged back to upstream because of a dropped support of `py27`, `py34` and `py35`

For now it is stable, and can be used as a `boto3` replacement, so I am going to add some modifications:

```python
s3_client = boto3.client("s3", ...) # old way, return type is botocore.BaseClient
s3_client = boto3.s3_client(...) # new way, return type is S3Client

# same for boto3.Session.client, boto3.resource and boto3.Session.resource

waiter = s3_client.get_waiter("bucket_exists") # old way, return type is botocore.Waiter
waiter = s3_client.get_bucket_exists_waiter() # new way, return type is BucketExistsWaiter

# same for s3_client.get_paginator
```

So, it stays fully backwards-compatible, but provides typing with no annotations that is supported by all Python IDEs that I know.

Let me know what you think.
