### ISSUE TITLE
Build annotations for aiobotocore

### ISSUE THREAD

**Issue by roganov** [vemel/mypy_boto3_builder#4]
Hello @vemel 
First of all, thank you for the great work on this.

Unfortunately boto and botocore don't have builtin async support, but there is [aiobotocore](https://github.com/aio-libs/aiobotocore). What do you think about supporting it as well inside `mypy_boto3_builder` or would you prefer a separate repository?

**Comment by vemel** [comment]
Hi! I am using aiobotocore only a little, and, TBH, I have never checked their source code. From what I understand, they have the same `client`, `resource` and `get_session` methods, that share the same typeshed. 

If you can help me to understand what exactly has to be done to add type annotations for `aiobotocore` as well - I am all for it.

As far as I understand, if i wrap client methods (other that get_paginator, get_waiter, etc.) return type with `AsyncIterator` - that should do it, right?

**Comment by roganov** [comment]
Things that I can name right now:
- obviously, methods need to be made `async`
- waiter.wait needs to be made `async` as well
- paginators need to return `AsyncIterator`
- methods returning `io` (such as `s3.get_object(...)['Body']`) return `aiohttp.ClientResponse`

This is probably not the full list, but should be enough to start testing.

**Comment by vemel** [comment]
This definitely should be a separate library. All type generators can be reused, I just need new stub generators for clients and services.

**Comment by takeda** [comment]
@roganov I think it would be better if `aiobotocore` would include types directly in their code. Have you tried to open an issue with them? For example `aiohttp` library from the same group offers excellent type support. Since they are providing `asyncio` functionality, there's no good reason to not provide type annotations which were introduced around the same time.

I think stubs are only good to provide type annotations when author of the project refuses to do so. When they are in the code they are less likely to be out of sync and also no need to install extra dependencies.

**Comment by vemel** [comment]
I agree. I tried to create a separate package, but could not finish it. I have never worked with `aiobotocore`, so it is hard for me to check if everything works correctly in real-life scenarios.

**Comment by vemel** [comment]
I will keep this issue opened because it is a good idea to support `aiobotocore`. Probably this can be done in scope of `botocore-stubs` which are provided by `mypy_boto3_builder` as well. 

However, this issue is stalling for quite a while, so I mark it as `wontfix`. Let's keep it here while we are gathering ideas.

**Comment by vemel** [comment]
Reopening this issue. It is now the main milestone for `mypy_boto3_builder 7.0.0`
Generated packages will be `aiobotocore-stubs`, `aiobotocore-ec2-stubs`, `aiobotocore-s3-stubs`, etc.

Differences from `boto3-stubs`:
- no `service_resource` module, only `client`, `paginator`, `waiter`, `type_defs` and `literals`
- all client methods are async
- use `AIOPaginator` instead of `Paginator`
- waiters are async as well

**Comment by vemel** [comment]
Hey guys, after 2 years of doing literally nothing for async boto3, I present `types-aiobotocore`: https://pypi.org/project/types-aiobotocore/

Works with `aiobotocore` and `aioboto3`. Please let me know if it works as it should, I tested only basic functionality for `s3` service.

**Comment by vemel** [comment]
I am going to close this issue. Please open new issues if you encounter any bugs in `types-aiobotocore`.
