### ISSUE TITLE
[BUG] Imports fail on latest 3.0.1 release

### ISSUE THREAD

**Issue by orf** [vemel/mypy_boto3_builder#48]
**Describe the bug**
It's not clear from the latest 3.x release notes if this is intended, but it seems `mypy_boto3_[service].client` modules have been removed. The [boto3-stubs](https://pypi.org/project/boto3-stubs/) package still recommends importing it like this.

**To Reproduce**
1. Install 'boto3-stubs[glue]'
2.  Run the following code snippet:

```python
from mypy_boto3_glue.client import GlueClient
```

3. Actual mypy output

```
    from mypy_boto3_glue.client import GlueClient
ModuleNotFoundError: No module named 'mypy_boto3_glue.client'
```

**Expected mypy-output**

```
No error I guess
```

**Additional context**

MacOS or Linux, tested on Py 3.7 and 3.8.

**Comment by vemel** [comment]
Thank you for the report! 

New version that fixes this issue should be published to PyPI in a few minutes.

Unfortunately, I completely overlooked that `pyi` files are not importable, so imports were broken during adding `pyright` support. The solution is hacky, but it is working - all service packages contain `py` files identical to `py`i.

This means, packages are twice as big now, but `mypy` and `pyright` work exactly the same with explicit and implicit type discovery. I hope that type checkers will not go crazy because of `py`/`pyi` overlap.

Please let me know if the fix works for you.

**Comment by orf** [comment]
Yes! This fixed it. Thank you @vemel!
